name: Notion Daily Tasks (00:01 Berlin)

on:
  schedule:
    - cron: "1 2 * * *"   # one of these hits 00:01 Berlin across DST
    - cron: "1 3 * * *"
  workflow_dispatch: {}

concurrency:
  group: daily-tasks
  cancel-in-progress: true

jobs:
  daily:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      # Compute Berlin date once and export it
      - name: Compute Berlin date
        id: when
        run: |
          echo "BERLIN_TIME=$(TZ=Europe/Berlin date +'%H%M')" >> $GITHUB_ENV
          echo "BERLIN_DATE=$(TZ=Europe/Berlin date +'%F')"   >> $GITHUB_ENV
          echo "time=$BERLIN_TIME" >> $GITHUB_OUTPUT
          echo "date=$BERLIN_DATE" >> $GITHUB_OUTPUT
          echo "Now Berlin time: $BERLIN_TIME, date: $BERLIN_DATE"

      # Gate: accept runs between 00:00–00:10 Berlin
      - name: Gate to 00:00–00:10 Berlin window
        run: |
          if [ "$BERLIN_TIME" -lt "0400" ] || [ "$BERLIN_TIME" -gt "0410" ]; then
            echo "Outside window (Berlin $BERLIN_TIME). Skipping."
            exit 0
          fi
          echo "Within window → continue."

      # Lock: skip if we've already run today (first run saves the cache)
      - name: Daily run lock
        id: cache
        uses: actions/cache@v4
        with:
          path: .run-lock/daily
          key: daily-${{ env.BERLIN_DATE }}

      - name: Note lock (first run only)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .run-lock/daily
          echo "ran ${BERLIN_DATE}" > .run-lock/daily/when.txt

      - name: Create today's tasks
        if: steps.cache.outputs.cache-hit != 'true'
        run: node notion-daily-tasks.js
