name: Notion Weekly Chart (23:59 Berlin)

on:
  schedule:
    - cron: "59 21 * * *"
    - cron: "59 22 * * *"
  workflow_dispatch: {}

concurrency:
  group: weekly-chart
  cancel-in-progress: true

jobs:
  chart:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
      DASHBOARD_PAGE_ID: ${{ secrets.DASHBOARD_PAGE_ID }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_UPLOAD_FOLDER: ${{ secrets.CLOUDINARY_UPLOAD_FOLDER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Compute Berlin time + ISO week
        id: when
        run: |
          echo "BERLIN_TIME=$(TZ=Europe/Berlin date +'%H%M')" >> $GITHUB_ENV
          echo "ISO_YEAR=$(TZ=Europe/Berlin date +'%G')"      >> $GITHUB_ENV
          echo "ISO_WEEK=$(TZ=Europe/Berlin date +'%V')"      >> $GITHUB_ENV
          echo "Now Berlin time: $BERLIN_TIME, ISO week: ${ISO_YEAR}-W${ISO_WEEK}"

      # Accept runs between 23:55 and 00:05 Berlin
      - name: Gate to 23:55–00:05 Berlin window
        run: |
          if { [ "$BERLIN_TIME" -ge "2355" ] || [ "$BERLIN_TIME" -le "0005" ]; }; then
            echo "Within window → continue."
          else
            echo "Outside window (Berlin $BERLIN_TIME). Skipping."
            exit 0
          fi

      # Lock: one chart per ISO week
      - name: Weekly run lock
        id: cache
        uses: actions/cache@v4
        with:
          path: .run-lock/chart
          key: chart-${{ env.ISO_YEAR }}-W${{ env.ISO_WEEK }}

      - name: Note lock (first run only)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .run-lock/chart
          echo "ran ${ISO_YEAR}-W${ISO_WEEK}" > .run-lock/chart/when.txt

      - name: Build & embed weekly chart
        if: steps.cache.outputs.cache-hit != 'true'
        run: node chart_cloudinary.js
